# Generated by Django 2.2.6 on 2019-10-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('webtoon_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=50)),
                ('webtoon_name', models.CharField(max_length=100)),
                ('webtoon_author', models.CharField(max_length=100)),
                ('webtoon_img_url', models.CharField(max_length=100)),
            ],
        ),
    ]
